### PR TITLE
Add Lowercase Version Long Option

### PR DESCRIPTION
**Pull request by vice**

### CODE REVIEW

**Comment by mraineri** [comment]
Any particular reason for the change?

**Comment by vice** [comment]
To be consistent with the options help text (https://github.com/DMTF/Redfishtool/blob/844c0b9c51cd7b42e5ed3d9ba4ff19e1dcccc618/redfishtool/redfishtoolMain.py#L37).

And because usually long options are lowercased.

**Comment by mraineri** [comment]
Ah, good catch; never noticed that discrepancy!

**Comment by billdodd** [comment]
Since the code has been like this for a long time it might be nice to be sure we still accept the original long arg:

```
elif opt in ("-V", "--version", "--Version"):
```

Just in the unlikely case that someone has a script that is collecting the tool version using '--Version'.

**Comment by mraineri** [comment]
Approved 6/6

**Pull request merged**
